app = 'tutpapers'
primary_region = 'jnb'

[build]
  dockerfile = "./Dockerfile" 


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = 8080

[[mounts]]
  source = "data"  # Name of your Fly volume
  destination = "/data"  # Mount point inside the container
